/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier.Report;

import Controllers.StudentController;
import Controllers.StudentTransactionController;
import Database.StudentTransactionDB;
import Forms.ReceiptForms;
import Models.StudentTransaction;
import Section.SliderLeft;
import Section.DesignSection;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Eunar B. Dayangco
 */
public class CashierReportUI extends javax.swing.JFrame {

    /**
     * Creates new form CashierReportUI
     */
    
    private SliderLeft slider;
    private ReportQuery query;
    private ArrayList<StudentTransaction> reports;
   
    public CashierReportUI() {
        initComponents();
        init();
        this.setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        transactionScrollPane = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        todaybtn = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        totalAmountOnReports = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 51));
        bodyPanel.setToolTipText("");
        bodyPanel.setOpaque(false);
        bodyPanel.setPreferredSize(new java.awt.Dimension(930, 620));
        bodyPanel.setLayout(null);

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "OR#", "Amount", "Payer"
            }
        ));
        transactionScrollPane.setViewportView(transactionTable);

        bodyPanel.add(transactionScrollPane);
        transactionScrollPane.setBounds(30, 20, 860, 440);

        jButton9.setBackground(new java.awt.Color(102, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("SHOW INFO");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        bodyPanel.add(jButton9);
        jButton9.setBounds(30, 470, 170, 41);

        todaybtn.setBackground(new java.awt.Color(102, 0, 0));
        todaybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        todaybtn.setForeground(new java.awt.Color(255, 255, 255));
        todaybtn.setText("TODAY");
        todaybtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        todaybtn.setFocusPainted(false);
        todaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todaybtnActionPerformed(evt);
            }
        });
        bodyPanel.add(todaybtn);
        todaybtn.setBounds(390, 470, 170, 41);

        jButton11.setBackground(new java.awt.Color(102, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("GEN. EXCEL");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setFocusPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        bodyPanel.add(jButton11);
        jButton11.setBounds(30, 520, 170, 41);

        jButton12.setBackground(new java.awt.Color(102, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("QUERY VALUES");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        bodyPanel.add(jButton12);
        jButton12.setBounds(390, 520, 170, 41);

        totalAmountOnReports.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalAmountOnReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmountOnReports.setText("00.0");
        totalAmountOnReports.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bodyPanel.add(totalAmountOnReports);
        totalAmountOnReports.setBounds(600, 510, 270, 50);

        savebtn.setBackground(new java.awt.Color(102, 0, 0));
        savebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("SAVE");
        savebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savebtn.setFocusPainted(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        bodyPanel.add(savebtn);
        savebtn.setBounds(210, 470, 170, 41);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("TOTAL:");
        bodyPanel.add(jLabel10);
        jLabel10.setBounds(600, 470, 110, 40);

        jButton14.setBackground(new java.awt.Color(102, 0, 0));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("PRINT");
        jButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.setFocusPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        bodyPanel.add(jButton14);
        jButton14.setBounds(210, 520, 170, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new ReceiptForms().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void todaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todaybtnActionPerformed
      
        displayOnTable();
        
    }//GEN-LAST:event_todaybtnActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     
       this.slider = new SliderLeft(new ReportQuery(this).getContentPane());
       this.slider.setVisible(true);
       
    }//GEN-LAST:event_jButton12ActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        new StudentTransactionController().turnToReports(this);
    }//GEN-LAST:event_savebtnActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierReportUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton todaybtn;
    private javax.swing.JLabel totalAmountOnReports;
    private javax.swing.JScrollPane transactionScrollPane;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables

    public void init(){
        new DesignSection().designTable(transactionTable, transactionScrollPane);
        this.reports = new ArrayList<>();
        
    }

    public SliderLeft getSlider() {
        return slider;
    }
    

    public void displayOnTable(){
    
        double totalAmount = 0;
        DefaultTableModel model = (DefaultTableModel)transactionTable.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[4];
        
        
       
        StudentTransactionController controller = new StudentTransactionController();
        
      
        this.reports = controller.getTodaysReport(this);
        
        
        for(StudentTransaction transac: this.reports){
           
            row[0] = transac.getTransDate();
            row[1] = transac.getOfficialReceipt();
            try {
                row[2] = new StudentTransactionDB().getTotalAmount(transac.getOfficialReceipt());
                totalAmount+=new StudentTransactionDB().getTotalAmount(transac.getOfficialReceipt());
            } catch (Exception ex) {
                Logger.getLogger(CashierReportUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            row[3] = transac.getStudent().getFullname();
            model.addRow(row);
        }
        totalAmountOnReports.setText(totalAmount+"");

    }
    
    public void displayOnTable(String fromDate,String toDate){
        
        double totalAmount = 0;
        DefaultTableModel model = (DefaultTableModel)transactionTable.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[4];
        
        
        StudentTransactionController controller = new StudentTransactionController();
        
      
        this.reports = controller.getReportsTransaction(this,fromDate,toDate);
        
        for(StudentTransaction transac:this.reports){
           
            row[0] = transac.getTransDate();
            row[1] = transac.getOfficialReceipt();
            try {
                row[2] = new StudentTransactionDB().getTotalAmount(transac.getOfficialReceipt());
                totalAmount+=new StudentTransactionDB().getTotalAmount(transac.getOfficialReceipt());
            } catch (Exception ex) {
                Logger.getLogger(CashierReportUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            row[3] = transac.getStudent().getFullname();
            model.addRow(row);
        }
        totalAmountOnReports.setText(totalAmount+"");
    
    }

    public ArrayList<StudentTransaction> getReports() {
        return reports;
    }

    public void setReports(ArrayList<StudentTransaction> reports) {
        this.reports = reports;
    }
    
    
    
}
