/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier.Report;

import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eunar B. Dayangco
 */
public class ReportQuery extends javax.swing.JFrame {

    /**
     * Creates new form ReportQuery
     */
    private CashierReportUI cashierReportUI;
    public ReportQuery() {
        initComponents();
    }
    
    public ReportQuery(CashierReportUI cashierReportUI) {
        initComponents();
        this.cashierReportUI = cashierReportUI;
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fromDate_comp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        toDate_comp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchdatebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        datePanel.setBackground(new java.awt.Color(0, 0, 0));
        datePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        datePanel.setOpaque(false);
        datePanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FROM:");
        datePanel.add(jLabel1);
        jLabel1.setBounds(40, 80, 60, 30);

        fromDate_comp.setBackground(new java.awt.Color(153, 153, 153));
        fromDate_comp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fromDate_comp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        datePanel.add(fromDate_comp);
        fromDate_comp.setBounds(40, 110, 230, 40);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("...");
        datePanel.add(jButton2);
        jButton2.setBounds(280, 110, 43, 40);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("...");
        datePanel.add(jButton3);
        jButton3.setBounds(280, 200, 43, 40);

        toDate_comp.setBackground(new java.awt.Color(153, 153, 153));
        toDate_comp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toDate_comp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        datePanel.add(toDate_comp);
        toDate_comp.setBounds(40, 200, 230, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TO:");
        datePanel.add(jLabel2);
        jLabel2.setBounds(40, 170, 60, 30);

        searchdatebtn.setBackground(new java.awt.Color(153, 153, 153));
        searchdatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchdatebtn.setText("DISPLAY");
        searchdatebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdatebtnActionPerformed(evt);
            }
        });
        datePanel.add(searchdatebtn);
        searchdatebtn.setBounds(40, 270, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEARCH BY DATE");
        datePanel.add(jLabel3);
        jLabel3.setBounds(90, 30, 190, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdatebtnActionPerformed
        
        String fromDate = fromDate_comp.getText();
        String toDate = toDate_comp.getText();
        
        this.cashierReportUI.displayOnTable(fromDate, toDate);
        this.cashierReportUI.getSlider().exitSlider();
    }//GEN-LAST:event_searchdatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportQuery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datePanel;
    private javax.swing.JTextField fromDate_comp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchdatebtn;
    private javax.swing.JTextField toDate_comp;
    // End of variables declaration//GEN-END:variables

    
}
