/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier.Transaction;

import Controllers.StudentTransactionController;
import Models.Student;
import Models.StudentTransaction;
import Section.DesignSection;
import Section.SliderLeft;
import Section.StationSection;
import Views.Cashier.StudentInfo.CashierStudentInfoMain;
import Views.Cashier.StudentInfo.ViewStudentInfoUI;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Eunar B. Dayangco
 */
public class ORHistory extends javax.swing.JFrame {

    /**
     * Creates new form ORHistory
     */

    private CashierTransactionMain main;
    private ViewStudentInfoUI viewStudentInfo;
    public ORHistory() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
       
    }
    public ORHistory(boolean stat) {
        initComponents();
        transactionbtn.setVisible(stat);
        designComponents();
        this.setBackground(new Color(0,0,0,0));
        
    }
    public ORHistory(CashierTransactionMain main,boolean stat) {
        initComponents();
        this.main = main;
        transactionbtn.setVisible(stat);
        designComponents();
        this.setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called transactionMain within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentInfobodyPanel = new javax.swing.JPanel();
        detailScrollpane = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        transactionbtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        remarksDisplay = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        totalAmountDisplay = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        transDateDisplay = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        orScrollPane = new javax.swing.JScrollPane();
        orTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        studentInfobodyPanel.setBackground(new java.awt.Color(255, 255, 51));
        studentInfobodyPanel.setOpaque(false);
        studentInfobodyPanel.setLayout(null);

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Pay ", "Amount"
            }
        ));
        detailScrollpane.setViewportView(detailTable);

        studentInfobodyPanel.add(detailScrollpane);
        detailScrollpane.setBounds(240, 130, 580, 230);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("FIND OR");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        studentInfobodyPanel.add(jButton3);
        jButton3.setBounds(240, 520, 200, 40);

        transactionbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        transactionbtn.setText("GO BACK TRANSACTION");
        transactionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionbtnMouseClicked(evt);
            }
        });
        studentInfobodyPanel.add(transactionbtn);
        transactionbtn.setBounds(60, 30, 249, 22);

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TO:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 40, 26);

        jTextField3.setBackground(new java.awt.Color(204, 153, 0));
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.add(jTextField3);
        jTextField3.setBounds(60, 10, 170, 30);

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("...");
        jPanel3.add(jButton6);
        jButton6.setBounds(240, 10, 50, 30);

        studentInfobodyPanel.add(jPanel3);
        jPanel3.setBounds(400, 70, 310, 50);

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("SHOW");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setFocusPainted(false);
        studentInfobodyPanel.add(jButton5);
        jButton5.setBounds(720, 70, 100, 50);

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FROM:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 10, 60, 26);

        jTextField4.setBackground(new java.awt.Color(204, 153, 0));
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jTextField4);
        jTextField4.setBounds(60, 10, 170, 30);

        jButton7.setBackground(new java.awt.Color(0, 153, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("...");
        jPanel4.add(jButton7);
        jButton7.setBounds(240, 10, 50, 30);

        studentInfobodyPanel.add(jPanel4);
        jPanel4.setBounds(60, 70, 310, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TOTAL:");
        studentInfobodyPanel.add(jLabel6);
        jLabel6.setBounds(240, 380, 52, 17);

        remarksDisplay.setBackground(new java.awt.Color(255, 255, 51));
        remarksDisplay.setColumns(20);
        remarksDisplay.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        remarksDisplay.setLineWrap(true);
        remarksDisplay.setRows(5);
        remarksDisplay.setWrapStyleWord(true);
        remarksDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        studentInfobodyPanel.add(remarksDisplay);
        remarksDisplay.setBounds(510, 400, 310, 110);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("REMARKS:");
        studentInfobodyPanel.add(jLabel7);
        jLabel7.setBounds(510, 380, 75, 17);

        totalAmountDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalAmountDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmountDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        studentInfobodyPanel.add(totalAmountDisplay);
        totalAmountDisplay.setBounds(240, 400, 250, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("DATE INSERTED:");
        studentInfobodyPanel.add(jLabel8);
        jLabel8.setBounds(240, 450, 140, 17);

        transDateDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transDateDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transDateDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        studentInfobodyPanel.add(transDateDisplay);
        transDateDisplay.setBounds(240, 470, 250, 40);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("PRINT OR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        studentInfobodyPanel.add(jButton4);
        jButton4.setBounds(620, 520, 200, 40);

        orTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orTableMouseClicked(evt);
            }
        });
        orScrollPane.setViewportView(orTable);
        if (orTable.getColumnModel().getColumnCount() > 0) {
            orTable.getColumnModel().getColumn(0).setResizable(false);
        }

        studentInfobodyPanel.add(orScrollPane);
        orScrollPane.setBounds(60, 130, 170, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentInfobodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentInfobodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionbtnMouseClicked
        main. fromPaymentInfotoTransaction();
        StationSection.getLabel().setText("TRANSACTION");
    }//GEN-LAST:event_transactionbtnMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new SliderLeft(new FindOR().getContentPane()).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void orTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orTableMouseClicked
      int row = orTable.getSelectedRow();
      
      String receipt = orTable.getValueAt(row,0).toString();
      displayOnTable(receipt);
      
    }//GEN-LAST:event_orTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ORHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ORHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ORHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ORHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ORHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane detailScrollpane;
    private javax.swing.JTable detailTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JScrollPane orScrollPane;
    private javax.swing.JTable orTable;
    private javax.swing.JTextArea remarksDisplay;
    private javax.swing.JPanel studentInfobodyPanel;
    private javax.swing.JLabel totalAmountDisplay;
    private javax.swing.JLabel transDateDisplay;
    private javax.swing.JLabel transactionbtn;
    // End of variables declaration//GEN-END:variables

    
    public void designComponents(){
        new DesignSection().designTable(detailTable, detailScrollpane);
        new DesignSection().designTable(orTable, orScrollPane);
    }
    
    public void displayOnList(){
        
         if(CashierStudentInfoMain.getDisplayedStudent() !=null){
        
            Student displayedStudent = CashierStudentInfoMain.getDisplayedStudent();
            ArrayList<StudentTransaction> transactions = 
                    new StudentTransactionController().getAllOfficialReceipt(displayedStudent.getStudentID());

            ArrayList<String> officialReceipts = new ArrayList<>();

             DefaultTableModel model = (DefaultTableModel)orTable.getModel();
             model.setRowCount(0);

             Object[] row = new Object[1];

             for(StudentTransaction transaction:transactions){
                officialReceipts.add(transaction.getOfficialReceipt());

            }
             HashSet hs = new HashSet();
             hs.addAll(officialReceipts);
             officialReceipts.clear();
             officialReceipts.addAll(hs);

             for(String or:officialReceipts){
                 row[0] = or;
                 model.addRow(row);
             }
         
        }
        
    }
    public void displayOnTable(String officialReceipt){
        
        double total = 0;
        ArrayList<StudentTransaction> transactions = 
                new StudentTransactionController().getAllTransaction(officialReceipt);
        
        DefaultTableModel model = (DefaultTableModel)detailTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[4];
        for(StudentTransaction transaction:transactions){
            
            row[0] = transaction.getTransID();
            row[1] = transaction.getPaymentFor().getReceiptType();
            row[2] = transaction.getPaymentFor().getPaymentName();
            row[3] = transaction.getPaymentAmount();
            total+=transaction.getPaymentAmount();
            model.addRow(row);
            
        
        }
        
        new DesignSection().hideColumn(0, detailTable);
        
        remarksDisplay.setText(transactions.get(0).getRemarks());
        transDateDisplay.setText(transactions.get(0).getTransDate()+"");
        totalAmountDisplay.setText(total+"");
    
    }

}
