/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier.Transaction;

import Controllers.SchoolTransactionController;
import Models.SchoolTransaction;
import Section.AnimationSection;
import Section.DesignSection;
import Section.StationSection;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eunar B. Dayangco
 */
public class OtherEntries extends javax.swing.JFrame {

    /**
     * Creates new form OtherEntries
     */
    private CashierTransactionMain main;
    private SchoolTransactionEntries entries;
    public OtherEntries() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }
    public OtherEntries(CashierTransactionMain main) {
        initComponents();
        this.main= main;
        designComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        otherEntriesPanel = new javax.swing.JPanel();
        transactionbtn = new javax.swing.JLabel();
        otherEntryScrollPane = new javax.swing.JScrollPane();
        otherEntryTable = new javax.swing.JTable();
        newbtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        otherEntriesPanel.setBackground(new java.awt.Color(255, 255, 51));
        otherEntriesPanel.setToolTipText("");
        otherEntriesPanel.setOpaque(false);
        otherEntriesPanel.setPreferredSize(new java.awt.Dimension(930, 620));

        transactionbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        transactionbtn.setText("GO BACK TRANSACTION");
        transactionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionbtnMouseClicked(evt);
            }
        });

        otherEntryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voucher #", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        otherEntryScrollPane.setViewportView(otherEntryTable);

        newbtn.setBackground(new java.awt.Color(102, 0, 0));
        newbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newbtn.setText("NEW");
        newbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("PRINT");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton8.setBackground(new java.awt.Color(102, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("SHOW INFO");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout otherEntriesPanelLayout = new javax.swing.GroupLayout(otherEntriesPanel);
        otherEntriesPanel.setLayout(otherEntriesPanelLayout);
        otherEntriesPanelLayout.setHorizontalGroup(
            otherEntriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherEntriesPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(transactionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(otherEntriesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(otherEntryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(otherEntriesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(newbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        otherEntriesPanelLayout.setVerticalGroup(
            otherEntriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherEntriesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(transactionbtn)
                .addGap(28, 28, 28)
                .addComponent(otherEntryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(otherEntriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(otherEntriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(otherEntriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionbtnMouseClicked
        StationSection.getLabel().setText("TRANSACTION");
        main. fromOtherEntriestoTransaction();
    }//GEN-LAST:event_transactionbtnMouseClicked

    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
        this.entries = new SchoolTransactionEntries(this);
        new AnimationSection().framesMovetoBottom(this.entries, 70, 20);
        
                
    }//GEN-LAST:event_newbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtherEntries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton newbtn;
    private javax.swing.JPanel otherEntriesPanel;
    private javax.swing.JScrollPane otherEntryScrollPane;
    private javax.swing.JTable otherEntryTable;
    private javax.swing.JLabel transactionbtn;
    // End of variables declaration//GEN-END:variables

    private void designComponents() {
        new DesignSection().designTable(otherEntryTable, otherEntryScrollPane);
        new DesignSection().designTable(otherEntryTable, otherEntryScrollPane);
                
    }
    public void init(){
        this.entries = new SchoolTransactionEntries();
    }
    
    public void displayOnTable(){
        
        ArrayList<SchoolTransaction> allEntries = 
                new SchoolTransactionController().getAllSchoolTransactions();
         
        DefaultTableModel model = (DefaultTableModel)otherEntryTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];
        for(SchoolTransaction transaction:allEntries){
            row[0] = transaction.getVoucherNumber();
            row[1] = transaction.getTransDate();
            row[2] = transaction.getAmount();
            model.addRow(row);
        }
                
    }
}
