/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier.Home;

import Views.Cashier.SchoolYear.CreateSchoolYear;
import Section.AnimationSection;
import Section.SliderLeft;
import Views.ColorTheme.ColorTheme;

import java.awt.Color;

/**
 *
 * @author Eunar B. Dayangco
 */
public class CashierHome extends javax.swing.JFrame {

    /**
     * Creates new form CashierHome
     */
    
    private ChatForm chatForm;
    private AllTransactions transactions;
    private AllStudents students;
    private SliderLeft slider;
    private CreateSchoolYear createSchoolYear;
    public CashierHome() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        openChatbtn = new javax.swing.JButton();
        openSchoolYearbtn = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        openTransactionbtn = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        colorThemebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 51));
        bodyPanel.setOpaque(false);
        bodyPanel.setLayout(null);

        openChatbtn.setBackground(new java.awt.Color(102, 0, 0));
        openChatbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openChatbtn.setForeground(new java.awt.Color(255, 255, 255));
        openChatbtn.setText("OPEN CHAT FORM");
        openChatbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openChatbtn.setFocusPainted(false);
        openChatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openChatbtnActionPerformed(evt);
            }
        });
        bodyPanel.add(openChatbtn);
        openChatbtn.setBounds(290, 470, 310, 41);

        openSchoolYearbtn.setBackground(new java.awt.Color(102, 0, 0));
        openSchoolYearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openSchoolYearbtn.setForeground(new java.awt.Color(255, 255, 255));
        openSchoolYearbtn.setText("OPEN A SCHOOL YEAR");
        openSchoolYearbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openSchoolYearbtn.setFocusPainted(false);
        openSchoolYearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSchoolYearbtnActionPerformed(evt);
            }
        });
        bodyPanel.add(openSchoolYearbtn);
        openSchoolYearbtn.setBounds(290, 230, 310, 41);

        jButton9.setBackground(new java.awt.Color(102, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("VIEW ALL STUDENTS");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        bodyPanel.add(jButton9);
        jButton9.setBounds(290, 410, 310, 41);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tel. No. : 236-1727");
        bodyPanel.add(jLabel2);
        jLabel2.setBounds(230, 170, 390, 40);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("YOUNGHOMES LEARNING CENTER, INC.");
        bodyPanel.add(jLabel3);
        jLabel3.setBounds(40, 70, 870, 40);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("L. Flores St., Pasil Cebu City");
        bodyPanel.add(jLabel4);
        jLabel4.setBounds(230, 130, 390, 40);

        openTransactionbtn.setBackground(new java.awt.Color(102, 0, 0));
        openTransactionbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openTransactionbtn.setForeground(new java.awt.Color(255, 255, 255));
        openTransactionbtn.setText("VIEW ALL TRANSACTIONS");
        openTransactionbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openTransactionbtn.setFocusPainted(false);
        openTransactionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTransactionbtnActionPerformed(evt);
            }
        });
        bodyPanel.add(openTransactionbtn);
        openTransactionbtn.setBounds(290, 350, 310, 41);

        jButton11.setBackground(new java.awt.Color(102, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("BACK - UP ");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setFocusPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        bodyPanel.add(jButton11);
        jButton11.setBounds(290, 290, 310, 41);

        colorThemebtn.setBackground(new java.awt.Color(102, 0, 0));
        colorThemebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        colorThemebtn.setForeground(new java.awt.Color(255, 255, 255));
        colorThemebtn.setText("COLOR THEME");
        colorThemebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        colorThemebtn.setFocusPainted(false);
        colorThemebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorThemebtnActionPerformed(evt);
            }
        });
        bodyPanel.add(colorThemebtn);
        colorThemebtn.setBounds(290, 530, 310, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openChatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openChatbtnActionPerformed
        exitOpenedFrame();
        this.slider = new SliderLeft(this.chatForm.getContentPane());
        this.slider.setVisible(true);
    }//GEN-LAST:event_openChatbtnActionPerformed

    private void openSchoolYearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSchoolYearbtnActionPerformed
        new AnimationSection().framesMovetoBottom(this.createSchoolYear, 70, 35);
    }//GEN-LAST:event_openSchoolYearbtnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    exitOpenedFrame();
       new AnimationSection().framesMovetoBottom(this.students, 70, 35);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void openTransactionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTransactionbtnActionPerformed
        exitOpenedFrame();
        //this.transactions.displayOnTable();
        new AnimationSection().framesMovetoBottom(this.transactions, 70, 35);
       
    }//GEN-LAST:event_openTransactionbtnActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void colorThemebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorThemebtnActionPerformed
       new AnimationSection().framesMovetoBottom(new ColorTheme(), 70, 35);
    }//GEN-LAST:event_colorThemebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton colorThemebtn;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton openChatbtn;
    private javax.swing.JButton openSchoolYearbtn;
    private javax.swing.JButton openTransactionbtn;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setBackground(new Color(0,0,0,0));
        this.chatForm = new ChatForm();
        this.transactions = new AllTransactions();
        this.students = new AllStudents();
        this.slider = new SliderLeft(this.chatForm.getContentPane());
        this.createSchoolYear = new CreateSchoolYear();
    }
    private void exitOpenedFrame(){
        this.transactions.setVisible(false);
        this.students.setVisible(false);
        this.slider.exitSlider();
                
    }
}
