/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier.Notification;

import Section.AnimationSection;
import Section.DesignSection;
import java.awt.Color;
import java.awt.Container;

/**
 *
 * @author Eunar B. Dayangco
 */
public class CashierNotificationUI extends javax.swing.JFrame {

    /**
     * Creates new form CashierNotificationUI
     */
    
    
    private CashierNotificationMain main;
    
    public CashierNotificationUI() {
        initComponents();
        designComponents();
        init();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentInfobodyPanel2 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        dueNotificationbtn = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        notificationListbtn = new javax.swing.JButton();
        plotterPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        studentInfobodyPanel2.setBackground(new java.awt.Color(255, 255, 51));
        studentInfobodyPanel2.setOpaque(false);
        studentInfobodyPanel2.setLayout(null);

        jButton12.setBackground(new java.awt.Color(102, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("SEND DIRECT MESSAGE");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setFocusPainted(false);
        studentInfobodyPanel2.add(jButton12);
        jButton12.setBounds(590, 530, 240, 40);

        dueNotificationbtn.setBackground(new java.awt.Color(102, 0, 0));
        dueNotificationbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dueNotificationbtn.setForeground(new java.awt.Color(255, 255, 255));
        dueNotificationbtn.setText("DUE NOTIFICATION");
        dueNotificationbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dueNotificationbtn.setFocusPainted(false);
        dueNotificationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueNotificationbtnActionPerformed(evt);
            }
        });
        studentInfobodyPanel2.add(dueNotificationbtn);
        dueNotificationbtn.setBounds(350, 470, 210, 40);

        jButton14.setBackground(new java.awt.Color(102, 0, 0));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("SAVE AS EXCEL");
        jButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.setFocusPainted(false);
        studentInfobodyPanel2.add(jButton14);
        jButton14.setBounds(110, 530, 210, 40);

        jButton15.setBackground(new java.awt.Color(102, 0, 0));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("SHOW PAYMENT DETAILS");
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton15.setFocusPainted(false);
        studentInfobodyPanel2.add(jButton15);
        jButton15.setBounds(590, 470, 240, 40);

        jButton16.setBackground(new java.awt.Color(102, 0, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("PRINT NOTIFICATION");
        jButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton16.setFocusPainted(false);
        studentInfobodyPanel2.add(jButton16);
        jButton16.setBounds(350, 530, 210, 40);

        notificationListbtn.setBackground(new java.awt.Color(102, 0, 0));
        notificationListbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notificationListbtn.setForeground(new java.awt.Color(255, 255, 255));
        notificationListbtn.setText("NOTIFICATION LIST");
        notificationListbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        notificationListbtn.setFocusPainted(false);
        notificationListbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationListbtnActionPerformed(evt);
            }
        });
        studentInfobodyPanel2.add(notificationListbtn);
        notificationListbtn.setBounds(110, 470, 210, 40);

        plotterPanel.setOpaque(false);

        javax.swing.GroupLayout plotterPanelLayout = new javax.swing.GroupLayout(plotterPanel);
        plotterPanel.setLayout(plotterPanelLayout);
        plotterPanelLayout.setHorizontalGroup(
            plotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        plotterPanelLayout.setVerticalGroup(
            plotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        studentInfobodyPanel2.add(plotterPanel);
        plotterPanel.setBounds(10, 10, 890, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentInfobodyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentInfobodyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dueNotificationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueNotificationbtnActionPerformed
          this.main.backtoNotificationDueStudent();
        
        notificationListbtn.setEnabled(true);
        dueNotificationbtn.setEnabled(false);
    }//GEN-LAST:event_dueNotificationbtnActionPerformed

    private void notificationListbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationListbtnActionPerformed
        this.main.toNotificationList();
        
        notificationListbtn.setEnabled(false);
        dueNotificationbtn.setEnabled(true);
    }//GEN-LAST:event_notificationListbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierNotificationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierNotificationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierNotificationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierNotificationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierNotificationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dueNotificationbtn;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton notificationListbtn;
    private javax.swing.JPanel plotterPanel;
    private javax.swing.JPanel studentInfobodyPanel2;
    // End of variables declaration//GEN-END:variables
      
     public void designComponents(){
         //new DesignSection().designTable(tableofNotification,tableScrollpane);
     }
     public void init(){
         this.main = new CashierNotificationMain();
         displayMain();
         this.dueNotificationbtn.setEnabled(false);
     }
     
    public void displayMain(){
        plotterPanel.removeAll();
        plotterPanel.add(this.main.getContentPane());
        plotterPanel.revalidate();
        plotterPanel.repaint();
    }
     
     
  }
