/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier.Notification;

import Section.DesignSection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Eunar B. Dayangco
 */
public class CreateNotification extends javax.swing.JFrame {

    /**
     * Creates new form CreateNotification
     */
    public CreateNotification() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        exitbtn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        receiverScrollPane = new javax.swing.JScrollPane();
        receiverTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(161, 214, 226));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(25, 149, 173));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        exitbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/close.png"))); // NOI18N
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });
        jPanel3.add(exitbtn);
        exitbtn.setBounds(750, 0, 50, 40);

        mainPanel.add(jPanel3);
        jPanel3.setBounds(0, 0, 800, 40);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jButton7.setBackground(new java.awt.Color(25, 149, 173));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("...");
        jPanel4.add(jButton7);
        jButton7.setBounds(250, 110, 50, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Due Date:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(40, 80, 80, 20);

        jTextField1.setBackground(new java.awt.Color(25, 149, 173));
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jTextField1);
        jTextField1.setBounds(40, 110, 200, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("# Days before Due:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(340, 80, 140, 30);

        jTextField4.setBackground(new java.awt.Color(25, 149, 173));
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jTextField4);
        jTextField4.setBounds(340, 110, 140, 40);

        jTextArea1.setBackground(new java.awt.Color(25, 149, 173));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane2.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(40, 270, 440, 140);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Message:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 240, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Title:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(40, 160, 40, 30);

        jTextField2.setBackground(new java.awt.Color(25, 149, 173));
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jTextField2);
        jTextField2.setBounds(40, 190, 440, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Receiver");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(520, 70, 80, 30);

        receiverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receiver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        receiverScrollPane.setViewportView(receiverTable);
        if (receiverTable.getColumnModel().getColumnCount() > 0) {
            receiverTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel4.add(receiverScrollPane);
        receiverScrollPane.setBounds(520, 100, 220, 330);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CREATE NOTIFICATION");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(40, 20, 300, 40);

        jButton2.setBackground(new java.awt.Color(25, 149, 173));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("SHOW ALL NOTIFICATION");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jButton2);
        jButton2.setBounds(250, 440, 230, 50);

        jButton1.setBackground(new java.awt.Color(25, 149, 173));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jButton1);
        jButton1.setBounds(630, 440, 110, 50);

        jButton4.setBackground(new java.awt.Color(25, 149, 173));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("FIND");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jButton4);
        jButton4.setBounds(520, 440, 100, 50);

        jButton3.setBackground(new java.awt.Color(25, 149, 173));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("CREATE");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jButton3);
        jButton3.setBounds(40, 440, 170, 50);

        mainPanel.add(jPanel4);
        jPanel4.setBounds(10, 40, 770, 530);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 800, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNotification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane receiverScrollPane;
    private javax.swing.JTable receiverTable;
    // End of variables declaration//GEN-END:variables

    public void designComponents(){
        
        new DesignSection().designForm(this, mainPanel, "mini");
        new DesignSection().designTable(receiverTable, receiverScrollPane);
        JTableHeader header = receiverTable.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 14));
          
        header.setBackground(new Color(25,149,173));
        header.setForeground(Color.WHITE);
        header.setPreferredSize(new Dimension(0,30));
    }
}
