/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Manager;

import Controllers.ManagerMainController;
import Section.CreateSection;
import Section.DesignSection;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author Eunar B. Dayangco
 */
public class ManagerMain extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMain
     */
    private ManagerMainController controller;
    public ManagerMain() {
        initComponents();
        new DesignSection().designForm(this, mainPanel, "mini");
        //mainPanel.setBackground(new Color(0,0,0,0));
        init();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logoDisplay = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reportsbtn = new javax.swing.JLabel();
        accountbtn = new javax.swing.JLabel();
        genPaybtn = new javax.swing.JLabel();
        announcementbtn = new javax.swing.JLabel();
        decisionbtn = new javax.swing.JLabel();
        homebtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        plotters = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(65, 65, 67));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(null);

        logoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/YHLClogo - menuPanel.png"))); // NOI18N
        mainPanel.add(logoDisplay);
        logoDisplay.setBounds(0, 0, 240, 200);

        jPanel4.setBackground(new java.awt.Color(65, 65, 67));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/close.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2);
        jLabel2.setBounds(1080, 0, 40, 40);

        reportsbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportsbtn.setForeground(new java.awt.Color(255, 255, 255));
        reportsbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportsbtn.setText("REPORTS");
        reportsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsbtnMouseExited(evt);
            }
        });
        jPanel4.add(reportsbtn);
        reportsbtn.setBounds(510, 50, 110, 30);

        accountbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accountbtn.setForeground(new java.awt.Color(255, 255, 255));
        accountbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountbtn.setText("ACCOUNTS");
        accountbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountbtnMouseExited(evt);
            }
        });
        jPanel4.add(accountbtn);
        accountbtn.setBounds(390, 50, 110, 30);

        genPaybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genPaybtn.setForeground(new java.awt.Color(255, 255, 255));
        genPaybtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genPaybtn.setText("GEN. PAYMENTS");
        genPaybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genPaybtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genPaybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                genPaybtnMouseExited(evt);
            }
        });
        jPanel4.add(genPaybtn);
        genPaybtn.setBounds(630, 50, 150, 30);

        announcementbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        announcementbtn.setForeground(new java.awt.Color(255, 255, 255));
        announcementbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        announcementbtn.setText("ANNOUNCEMENT");
        announcementbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                announcementbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                announcementbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                announcementbtnMouseExited(evt);
            }
        });
        jPanel4.add(announcementbtn);
        announcementbtn.setBounds(910, 50, 150, 30);

        decisionbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decisionbtn.setForeground(new java.awt.Color(255, 255, 255));
        decisionbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        decisionbtn.setText("DECISION");
        decisionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decisionbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decisionbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decisionbtnMouseExited(evt);
            }
        });
        jPanel4.add(decisionbtn);
        decisionbtn.setBounds(790, 50, 110, 30);

        homebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homebtn.setText("HOME");
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        jPanel4.add(homebtn);
        homebtn.setBounds(270, 50, 110, 30);

        mainPanel.add(jPanel4);
        jPanel4.setBounds(0, 0, 1120, 110);

        jPanel1.setBackground(new java.awt.Color(254, 230, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1);
        jPanel1.setBounds(0, 110, 1120, 10);

        plotters.setOpaque(false);

        javax.swing.GroupLayout plottersLayout = new javax.swing.GroupLayout(plotters);
        plotters.setLayout(plottersLayout);
        plottersLayout.setHorizontalGroup(
            plottersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        plottersLayout.setVerticalGroup(
            plottersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        mainPanel.add(plotters);
        plotters.setBounds(0, 120, 1120, 540);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 1120, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void accountbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbtnMouseEntered
        setEnterButton(accountbtn);
    }//GEN-LAST:event_accountbtnMouseEntered

    private void accountbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbtnMouseExited
        setExitButton(accountbtn);
    }//GEN-LAST:event_accountbtnMouseExited

    private void reportsbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsbtnMouseEntered
      setEnterButton(reportsbtn);
    }//GEN-LAST:event_reportsbtnMouseEntered

    private void reportsbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsbtnMouseExited
       setExitButton(reportsbtn);
    }//GEN-LAST:event_reportsbtnMouseExited

    private void genPaybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genPaybtnMouseEntered
        setEnterButton(genPaybtn);
    }//GEN-LAST:event_genPaybtnMouseEntered

    private void genPaybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genPaybtnMouseExited
        setExitButton(genPaybtn);
    }//GEN-LAST:event_genPaybtnMouseExited

    private void decisionbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decisionbtnMouseEntered
        setEnterButton(decisionbtn);
    }//GEN-LAST:event_decisionbtnMouseEntered

    private void decisionbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decisionbtnMouseExited
       setExitButton(decisionbtn);
    }//GEN-LAST:event_decisionbtnMouseExited

    private void announcementbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_announcementbtnMouseEntered
       setEnterButton(announcementbtn);
    }//GEN-LAST:event_announcementbtnMouseEntered

    private void announcementbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_announcementbtnMouseExited
        setExitButton(announcementbtn);
    }//GEN-LAST:event_announcementbtnMouseExited

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
        setEnterButton(homebtn);
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
        setExitButton(homebtn);
    }//GEN-LAST:event_homebtnMouseExited

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
       this.controller.displayComponents(plotters, this.controller.getManagerHome());     
    }//GEN-LAST:event_homebtnMouseClicked

    private void reportsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsbtnMouseClicked
       this.controller.displayComponents(plotters, this.controller.getManagerReport());
    }//GEN-LAST:event_reportsbtnMouseClicked

    private void accountbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbtnMouseClicked
         this.controller.displayComponents(plotters, this.controller.getManagerAccount());
    }//GEN-LAST:event_accountbtnMouseClicked

    private void genPaybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genPaybtnMouseClicked
          this.controller.displayComponents(plotters, this.controller.getManagerGeneralPayments());
    }//GEN-LAST:event_genPaybtnMouseClicked

    private void decisionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decisionbtnMouseClicked
        this.controller.displayComponents(plotters, this.controller.getManagerDecision());
    }//GEN-LAST:event_decisionbtnMouseClicked

    private void announcementbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_announcementbtnMouseClicked
       this.controller.displayComponents(plotters, this.controller.getManagerAnnouncement());
    }//GEN-LAST:event_announcementbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountbtn;
    private javax.swing.JLabel announcementbtn;
    private javax.swing.JLabel decisionbtn;
    private javax.swing.JLabel genPaybtn;
    private javax.swing.JLabel homebtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logoDisplay;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel plotters;
    private javax.swing.JLabel reportsbtn;
    // End of variables declaration//GEN-END:variables

    public void setEnterButton(JLabel button){
        
      button.setSize(button.getWidth()+20,button.getHeight()+20);
      button.setFont(new Font("Tahoma", Font.BOLD, 18));
      button.setLocation(button.getX()-10, button.getY()-10);
      button.setForeground(Color.YELLOW);
        
    }
     public void setExitButton(JLabel button){
        
      button.setSize(button.getWidth()-20,button.getHeight()-20);
      button.setFont(new Font("Tahoma", Font.BOLD, 14));
      button.setLocation(button.getX()+10, button.getY()+10);
      button.setForeground(Color.WHITE);
        
    }
     
     public void init(){
         this.controller = new ManagerMainController();
         this.controller.displayComponents(plotters, this.controller.getManagerHome());
     }
    
    

    
     
}
