/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Manager.GeneralPayments;

import Controllers.GeneralPaymentController;
import Controllers.LevelController;
import Models.GeneralPayment;
import Models.Levels;
import Section.AnimationSection;
import Section.CreateSection;
import Section.DesignSection;
import Section.SetSection;
import Section.StationSection;
import Views.Manager.Levels.LevelsUI;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Eunar B. Dayangco
 */
public class AddGeneralPayment extends javax.swing.JFrame {

    /**
     * Creates new form AddGeneralPayment
     */
    private String message;
    private ManagerGeneralPayments generalPayment;
    private GeneralPaymentController controller;
    private LevelsUI levelsUI;
    
    public AddGeneralPayment() {
        initComponents();
        init();
        
        
    }
     public AddGeneralPayment(ManagerGeneralPayments generalPayment) {
        initComponents();
        init();
        this.generalPayment = generalPayment;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paymentName_comp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        paymentAmount_comp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paymentFor_comp = new javax.swing.JComboBox<>();
        levelSelectbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        addtoAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        receiptType_comp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(255, 240, 165));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(254, 175, 57));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/xbutton.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel2.add(closebtn);
        closebtn.setBounds(366, 0, 40, 40);

        mainPanel.add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(50, 70, 100, 20);

        paymentName_comp.setBackground(new java.awt.Color(254, 175, 57));
        paymentName_comp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        paymentName_comp.setForeground(new java.awt.Color(0, 0, 0));
        paymentName_comp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentName_comp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainPanel.add(paymentName_comp);
        paymentName_comp.setBounds(50, 90, 310, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("For:");
        mainPanel.add(jLabel2);
        jLabel2.setBounds(50, 230, 90, 20);

        paymentAmount_comp.setBackground(new java.awt.Color(254, 175, 57));
        paymentAmount_comp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        paymentAmount_comp.setForeground(new java.awt.Color(0, 0, 0));
        paymentAmount_comp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentAmount_comp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainPanel.add(paymentAmount_comp);
        paymentAmount_comp.setBounds(50, 170, 310, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Amount:");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(50, 150, 100, 20);

        paymentFor_comp.setBackground(new java.awt.Color(254, 175, 57));
        paymentFor_comp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        paymentFor_comp.setForeground(new java.awt.Color(0, 0, 0));
        paymentFor_comp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pre-School", "Kinder", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6" }));
        mainPanel.add(paymentFor_comp);
        paymentFor_comp.setBounds(50, 250, 230, 40);

        levelSelectbtn.setBackground(new java.awt.Color(254, 175, 57));
        levelSelectbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelSelectbtn.setForeground(new java.awt.Color(0, 0, 0));
        levelSelectbtn.setText("...");
        levelSelectbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        levelSelectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelSelectbtnActionPerformed(evt);
            }
        });
        mainPanel.add(levelSelectbtn);
        levelSelectbtn.setBounds(290, 250, 70, 40);

        addbtn.setBackground(new java.awt.Color(254, 175, 57));
        addbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addbtn.setForeground(new java.awt.Color(0, 0, 0));
        addbtn.setText("ADD");
        addbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        mainPanel.add(addbtn);
        addbtn.setBounds(240, 390, 120, 40);

        addtoAll.setBackground(new java.awt.Color(254, 175, 57));
        addtoAll.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addtoAll.setForeground(new java.awt.Color(0, 0, 0));
        addtoAll.setText("ADD TO ALL");
        addtoAll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addtoAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoAllActionPerformed(evt);
            }
        });
        mainPanel.add(addtoAll);
        addtoAll.setBounds(50, 390, 180, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Receipt Type:");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(50, 310, 130, 20);

        receiptType_comp.setBackground(new java.awt.Color(254, 175, 57));
        receiptType_comp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        receiptType_comp.setForeground(new java.awt.Color(0, 0, 0));
        receiptType_comp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provisional Receipt", "Official Receipt" }));
        mainPanel.add(receiptType_comp);
        receiptType_comp.setBounds(50, 330, 310, 40);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 410, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        new AnimationSection().framesMoveBacktoTop(this, 70, 20);
    }//GEN-LAST:event_closebtnMouseClicked

    private void levelSelectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelSelectbtnActionPerformed
        this.levelsUI = new LevelsUI(this);
        new AnimationSection().framesMovetoBottom(this.levelsUI, 70, 30);
    }//GEN-LAST:event_levelSelectbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
         this.controller.insertProcess(this);
    }//GEN-LAST:event_addbtnActionPerformed

    private void addtoAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoAllActionPerformed
        this.controller.insertMultipleProcess(this);
        
        
    }//GEN-LAST:event_addtoAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGeneralPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton addtoAll;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton levelSelectbtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField paymentAmount_comp;
    private javax.swing.JComboBox<String> paymentFor_comp;
    private javax.swing.JTextField paymentName_comp;
    private javax.swing.JComboBox<String> receiptType_comp;
    // End of variables declaration//GEN-END:variables
   
    
    public void init(){
        new DesignSection().designForm(this, mainPanel, "mini");
        this.controller = new GeneralPaymentController();
        this.levelsUI = new LevelsUI(this);
       SetSection.displayLevelList(getComboforLevel());
    }
    
    public GeneralPayment getNewPaymentEntry(){
        
        GeneralPayment newPayment = new GeneralPayment();
        newPayment.setPaymentName(paymentName_comp.getText());
        newPayment.setPaymentAmount(Double.parseDouble(paymentAmount_comp.getText()));
        newPayment.setPaymentLevel(paymentFor_comp.getSelectedItem().toString());
        newPayment.setReceiptType(receiptType_comp.getSelectedItem().toString());
        newPayment.setUser(StationSection.getLoggedUser());
        newPayment.setActive(true);
        return newPayment;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
    
    
    
    public boolean validateInput(){
        
        String displayMessage = "";
        
        if(paymentName_comp.getText().isEmpty()){
            displayMessage+="Payment Name is empty.\n";
        }
        if(paymentAmount_comp.getText().isEmpty()){
            displayMessage+="Payment Amount is empty.\n";
        }
         if(paymentFor_comp.getSelectedItem().toString().isEmpty()){
            displayMessage+="Payment For is empty.\n";
        }
         
         setMessage(displayMessage);
         
         return paymentName_comp.getText().isEmpty() ||
         paymentAmount_comp.getText().isEmpty() ||  
         paymentFor_comp.getSelectedItem().toString().isEmpty();
    
    }
    public void clearAll(){
        
        paymentName_comp.setText("");
        paymentAmount_comp.setText("");
        paymentFor_comp.setSelectedIndex(0);
    
    }
    public void displayOnPaymentTable(){
        this.generalPayment.displayOnTable();
    }
    
   public JComboBox getComboforLevel(){
       return paymentFor_comp;
   }
   
    public ArrayList<GeneralPayment> getMultipleInsertPayment(){
        ArrayList<GeneralPayment> batches = new ArrayList<>();
        
        for(Levels level:new LevelController().getAllLevels()){
            
            GeneralPayment newPayment = new GeneralPayment();
            newPayment.setPaymentName(paymentName_comp.getText());
            newPayment.setPaymentAmount(Double.parseDouble(paymentAmount_comp.getText()));
            newPayment.setReceiptType(receiptType_comp.getSelectedItem().toString());
            newPayment.setPaymentLevel(level.getLevelName());
            newPayment.setUser(StationSection.getLoggedUser());
            newPayment.setActive(true);
            batches.add(newPayment);
        
        }
        
        return batches;
        
      
   }
    
  
   
   
   
}
