/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Manager.GeneralPayments;

import Controllers.GeneralPaymentController;
import Controllers.LevelController;
import Models.GeneralPayment;
import Models.Levels;
import Section.AnimationSection;
import Section.CreateSection;
import Section.DesignSection;
import Section.SetSection;
import Section.StationSection;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Eunar B. Dayangco
 */
public class EditGeneralPayment extends javax.swing.JFrame {

    /**
     * Creates new form EditPayment
     */
    private GeneralPaymentController controler;
    private ManagerGeneralPayments generalPayment;
    private String message;
    
   
    public EditGeneralPayment() {
        initComponents();
        init();
    }
     public EditGeneralPayment(ManagerGeneralPayments generalPayment) {
        initComponents();
        init();
        this.generalPayment = generalPayment;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paymentName_comp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        paymentAmount_comp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paymentFor_comp = new javax.swing.JComboBox<>();
        savebtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        receiptType_comp = new javax.swing.JComboBox<>();
        addtoAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(255, 240, 165));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(254, 175, 57));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/xbutton.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel2.add(closebtn);
        closebtn.setBounds(366, 0, 40, 40);

        mainPanel.add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(50, 70, 100, 20);

        paymentName_comp.setBackground(new java.awt.Color(254, 175, 57));
        paymentName_comp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        paymentName_comp.setForeground(new java.awt.Color(0, 0, 0));
        paymentName_comp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentName_comp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainPanel.add(paymentName_comp);
        paymentName_comp.setBounds(50, 90, 310, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("For:");
        mainPanel.add(jLabel2);
        jLabel2.setBounds(50, 230, 90, 20);

        paymentAmount_comp.setBackground(new java.awt.Color(254, 175, 57));
        paymentAmount_comp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        paymentAmount_comp.setForeground(new java.awt.Color(0, 0, 0));
        paymentAmount_comp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentAmount_comp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainPanel.add(paymentAmount_comp);
        paymentAmount_comp.setBounds(50, 170, 310, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Amount:");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(50, 150, 100, 20);

        paymentFor_comp.setBackground(new java.awt.Color(254, 175, 57));
        paymentFor_comp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        paymentFor_comp.setForeground(new java.awt.Color(0, 0, 0));
        paymentFor_comp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pre-School", "Kinder", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6" }));
        mainPanel.add(paymentFor_comp);
        paymentFor_comp.setBounds(50, 250, 310, 40);

        savebtn.setBackground(new java.awt.Color(254, 175, 57));
        savebtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        savebtn.setForeground(new java.awt.Color(0, 0, 0));
        savebtn.setText("EDIT");
        savebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        mainPanel.add(savebtn);
        savebtn.setBounds(240, 400, 120, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Receipt Type:");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(50, 310, 130, 20);

        receiptType_comp.setBackground(new java.awt.Color(254, 175, 57));
        receiptType_comp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        receiptType_comp.setForeground(new java.awt.Color(0, 0, 0));
        receiptType_comp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provisional Receipt", "Official Receipt" }));
        mainPanel.add(receiptType_comp);
        receiptType_comp.setBounds(50, 330, 310, 40);

        addtoAll.setBackground(new java.awt.Color(254, 175, 57));
        addtoAll.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addtoAll.setForeground(new java.awt.Color(0, 0, 0));
        addtoAll.setText("EDIT TO ALL");
        addtoAll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addtoAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoAllActionPerformed(evt);
            }
        });
        mainPanel.add(addtoAll);
        addtoAll.setBounds(50, 400, 180, 40);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 410, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        new AnimationSection().framesMoveBacktoTop(this, 70, 20);
    }//GEN-LAST:event_closebtnMouseClicked

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        this.controler.editProcess(this);
    }//GEN-LAST:event_savebtnActionPerformed

    private void addtoAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoAllActionPerformed
       this.controler.editMultipleProcess(this);

    }//GEN-LAST:event_addtoAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGeneralPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGeneralPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtoAll;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField paymentAmount_comp;
    private javax.swing.JComboBox<String> paymentFor_comp;
    private javax.swing.JTextField paymentName_comp;
    private javax.swing.JComboBox<String> receiptType_comp;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables

    public void init() {
        new DesignSection().designForm(this, mainPanel, "mini");
        this.controler = new GeneralPaymentController();
        SetSection.displayLevelList(getComboforLevel());
    }
    public JComboBox getComboforLevel(){
        return paymentFor_comp;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
    
    public boolean validateInput(){
        
        String displayMessage = "";
        
        if(paymentName_comp.getText().isEmpty()){
            displayMessage+="Payment Name is empty.\n";
        }
        if(paymentAmount_comp.getText().isEmpty()){
            displayMessage+="Payment Amount is empty.\n";
        }
         if(paymentFor_comp.getSelectedItem().toString().isEmpty()){
            displayMessage+="Payment For is empty.\n";
        }
         
         setMessage(displayMessage);
         
         return paymentName_comp.getText().isEmpty() ||
         paymentAmount_comp.getText().isEmpty() ||  
         paymentFor_comp.getSelectedItem().toString().isEmpty();
    
    }
    public void displayData(){
        GeneralPayment genPayment = generalPayment.getSelectedGeneralPayment();
        paymentName_comp.setText(genPayment.getPaymentName());
        paymentAmount_comp.setText(genPayment.getPaymentAmount()+"");
        paymentFor_comp.setSelectedItem(genPayment.getPaymentLevel());
        receiptType_comp.setSelectedItem(genPayment.getReceiptType());
    }
    
    public GeneralPayment getEditedGeneralPayment(){
        GeneralPayment genPayment = generalPayment.getSelectedGeneralPayment();
        genPayment.setPaymentName(paymentName_comp.getText());
        genPayment.setPaymentAmount(Double.parseDouble(paymentAmount_comp.getText()));
        genPayment.setPaymentLevel(paymentFor_comp.getSelectedItem().toString());
        genPayment.setReceiptType(receiptType_comp.getSelectedItem().toString());
        
        return genPayment;
    }   
    
    public void displayOnPaymentTable(){
        this.generalPayment.displayOnTable();
    }
    
    public ArrayList<GeneralPayment> getMultipleEditPayments(){
         ArrayList<GeneralPayment> batches = new ArrayList<>();
         GeneralPayment selectedPayment = generalPayment.getSelectedGeneralPayment();
         
            
            for(GeneralPayment payment:new GeneralPaymentController().getAllGeneralPayments()){
                if(payment.getPaymentName().equals(selectedPayment.getPaymentName())){
                    
                    payment.setPaymentName(paymentName_comp.getText());
                    payment.setPaymentAmount(Double.parseDouble(paymentAmount_comp.getText()));
                    payment.setReceiptType(receiptType_comp.getSelectedItem().toString());
                    payment.setUser(StationSection.getLoggedUser());
                    payment.setActive(true);
                    
                    batches.add(payment);
                }
            }
       
        
        
        
        return batches;
        
    
    }
    
}
