/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier;

import Controllers.UserController;
import Models.User;
import Section.DesignSection;
import java.awt.Color;

/**
 *
 * @author Eunar B. Dayangco
 */
public class CashierLoginUI extends javax.swing.JFrame {

    /**
     * Creates new form CashierLoginUI
     */
    private UserController controller;
    private String message;
    
    public CashierLoginUI() {
        initComponents();
        init();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        bodyPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        imagebackground = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        bodyPanel.setOpaque(false);
        bodyPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Password:");
        bodyPanel.add(jLabel1);
        jLabel1.setBounds(300, 320, 90, 40);

        txtPassword.setBackground(new java.awt.Color(255, 255, 51));
        txtPassword.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        bodyPanel.add(txtPassword);
        txtPassword.setBounds(310, 360, 270, 40);

        txtUsername.setBackground(new java.awt.Color(255, 255, 51));
        txtUsername.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        bodyPanel.add(txtUsername);
        txtUsername.setBounds(310, 250, 270, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        bodyPanel.add(jLabel2);
        jLabel2.setBounds(310, 210, 80, 40);

        cancelbtn.setBackground(new java.awt.Color(0, 0, 0));
        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(255, 255, 51));
        cancelbtn.setText("CANCEL");
        cancelbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelbtn.setFocusPainted(false);
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        bodyPanel.add(cancelbtn);
        cancelbtn.setBounds(310, 430, 120, 40);

        loginbtn.setBackground(new java.awt.Color(0, 0, 0));
        loginbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 51));
        loginbtn.setText("LOGIN");
        loginbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginbtn.setFocusPainted(false);
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        bodyPanel.add(loginbtn);
        loginbtn.setBounds(460, 430, 120, 40);

        imagebackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagebackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierLogin/loginImageBackground.png"))); // NOI18N
        imagebackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bodyPanel.add(imagebackground);
        imagebackground.setBounds(0, 0, 760, 550);

        getContentPane().add(bodyPanel);
        bodyPanel.setBounds(0, 0, 760, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
            
        this.controller.loginProcess(this);
    
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierLoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel imagebackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    //methods here...
    
    
    public void init(){
        this.setBackground(new Color(0,0,0,0));
        new DesignSection().designForm(this, bodyPanel, "mini");
        this.controller = new UserController();
                
    }
    public boolean validateInput(){
        
        String displayMessage = "";
        if(getUsernameVal().isEmpty()){
            displayMessage+="Username is empty.\n";
        }
        if( getPasswordVal().isEmpty()){
            displayMessage+="Password is empty.\n";
        }
        
        setMessage(displayMessage);
        
        return getUsernameVal().isEmpty() ||
                getPasswordVal().isEmpty();
        
    }
    public String getUsernameVal(){
        return txtUsername.getText();
    }
    
    public String getPasswordVal(){
        return txtPassword.getText();
    }
    
  
    
    public User getUserEntry(){
        User user = new User();
        
        user.setUsername(txtUsername.getText());
        user.setPassword(txtPassword.getText());
        
        
        return user;
        
    }
    
    public void openCashierMain(){
         
        CashierMainUI cashierMain = new CashierMainUI();
        int x = (int) cashierMain.getLocation().getX();
        int y = (int) cashierMain.getLocation().getY();
        cashierMain.setLocation(x,y-30);
        cashierMain.setVisible(true);
        this.dispose();
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
    
    
    
   
    

}
