/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cashier;

import Controllers.CashierMainController;
import Controllers.SchoolTransactionController;
import Controllers.SchoolYearController;
import Section.CreateSection;
import Section.DesignSection;
import Section.StationSection;
import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.SwingConstants;


/**
 *
 * @author Eunar B. Dayangco
 */
public class CashierMainUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentInfoUI
     */
    
    
    private CashierMainController controller;

   
    
    public CashierMainUI() {
        initComponents();
        init();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholebodyPanel = new javax.swing.JPanel();
        schoolyearDisplayer = new javax.swing.JLabel();
        CurrentPlacelbl = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        minbtn = new javax.swing.JLabel();
        topBar = new javax.swing.JLabel();
        mainbodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        image_homebtn = new javax.swing.JButton();
        imageStudentInfobtn = new javax.swing.JButton();
        studentinfobtn = new javax.swing.JButton();
        image_transactionbtn = new javax.swing.JButton();
        transactionbtn = new javax.swing.JButton();
        image_reportbtn = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();
        image_notificationbtn = new javax.swing.JButton();
        signoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        notificationbtn = new javax.swing.JButton();
        menuBackgroundImage = new javax.swing.JLabel();
        plotterPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        wholebodyPanel.setBackground(new java.awt.Color(102, 0, 0));
        wholebodyPanel.setLayout(null);

        schoolyearDisplayer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        schoolyearDisplayer.setForeground(new java.awt.Color(255, 255, 255));
        schoolyearDisplayer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        wholebodyPanel.add(schoolyearDisplayer);
        schoolyearDisplayer.setBounds(850, 0, 270, 30);

        CurrentPlacelbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CurrentPlacelbl.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPlacelbl.setText("HOME");
        wholebodyPanel.add(CurrentPlacelbl);
        CurrentPlacelbl.setBounds(20, 0, 300, 30);

        closebtn.setBackground(new java.awt.Color(204, 0, 0));
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/close.png"))); // NOI18N
        closebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        closebtn.setBorderPainted(false);
        closebtn.setFocusPainted(false);
        closebtn.setOpaque(false);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        wholebodyPanel.add(closebtn);
        closebtn.setBounds(1120, 0, 50, 30);

        minbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minbtnMouseClicked(evt);
            }
        });
        wholebodyPanel.add(minbtn);
        minbtn.setBounds(1110, 0, 28, 30);

        topBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/topImage.png"))); // NOI18N
        topBar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        wholebodyPanel.add(topBar);
        topBar.setBounds(0, 0, 1170, 30);

        getContentPane().add(wholebodyPanel);
        wholebodyPanel.setBounds(0, 0, 1170, 30);

        mainbodyPanel.setBackground(new java.awt.Color(247, 220, 111));
        mainbodyPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        mainbodyPanel.setLayout(null);

        menuPanel.setBackground(new java.awt.Color(32, 33, 35));
        menuPanel.setLayout(null);

        homebtn.setBackground(new java.awt.Color(204, 153, 0));
        homebtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(null);
        homebtn.setFocusPainted(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        menuPanel.add(homebtn);
        homebtn.setBounds(80, 240, 150, 40);

        image_homebtn.setBackground(new java.awt.Color(204, 51, 0));
        image_homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/home.png"))); // NOI18N
        image_homebtn.setBorder(null);
        image_homebtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/home.png"))); // NOI18N
        image_homebtn.setFocusPainted(false);
        image_homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_homebtnActionPerformed(evt);
            }
        });
        menuPanel.add(image_homebtn);
        image_homebtn.setBounds(30, 240, 50, 40);

        imageStudentInfobtn.setBackground(new java.awt.Color(204, 51, 0));
        imageStudentInfobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/student.png"))); // NOI18N
        imageStudentInfobtn.setBorder(null);
        imageStudentInfobtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/student.png"))); // NOI18N
        imageStudentInfobtn.setFocusPainted(false);
        imageStudentInfobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageStudentInfobtnActionPerformed(evt);
            }
        });
        menuPanel.add(imageStudentInfobtn);
        imageStudentInfobtn.setBounds(30, 300, 50, 40);

        studentinfobtn.setBackground(new java.awt.Color(204, 153, 0));
        studentinfobtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        studentinfobtn.setText("Student Info");
        studentinfobtn.setBorder(null);
        studentinfobtn.setFocusPainted(false);
        studentinfobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentinfobtnActionPerformed(evt);
            }
        });
        menuPanel.add(studentinfobtn);
        studentinfobtn.setBounds(80, 300, 150, 40);

        image_transactionbtn.setBackground(new java.awt.Color(204, 51, 0));
        image_transactionbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/transaction.png"))); // NOI18N
        image_transactionbtn.setBorder(null);
        image_transactionbtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/transaction.png"))); // NOI18N
        image_transactionbtn.setFocusPainted(false);
        image_transactionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_transactionbtnActionPerformed(evt);
            }
        });
        menuPanel.add(image_transactionbtn);
        image_transactionbtn.setBounds(30, 360, 50, 40);

        transactionbtn.setBackground(new java.awt.Color(204, 153, 0));
        transactionbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        transactionbtn.setText("Transaction");
        transactionbtn.setBorder(null);
        transactionbtn.setFocusPainted(false);
        transactionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionbtnActionPerformed(evt);
            }
        });
        menuPanel.add(transactionbtn);
        transactionbtn.setBounds(80, 360, 150, 40);

        image_reportbtn.setBackground(new java.awt.Color(204, 51, 0));
        image_reportbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/report.png"))); // NOI18N
        image_reportbtn.setBorder(null);
        image_reportbtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/report.png"))); // NOI18N
        image_reportbtn.setFocusPainted(false);
        image_reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_reportbtnActionPerformed(evt);
            }
        });
        menuPanel.add(image_reportbtn);
        image_reportbtn.setBounds(30, 420, 50, 40);

        reportbtn.setBackground(new java.awt.Color(204, 153, 0));
        reportbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reportbtn.setText("Report");
        reportbtn.setBorder(null);
        reportbtn.setFocusPainted(false);
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });
        menuPanel.add(reportbtn);
        reportbtn.setBounds(80, 420, 150, 40);

        image_notificationbtn.setBackground(new java.awt.Color(204, 51, 0));
        image_notificationbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/notification.png"))); // NOI18N
        image_notificationbtn.setBorder(null);
        image_notificationbtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/notification.png"))); // NOI18N
        image_notificationbtn.setFocusPainted(false);
        image_notificationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_notificationbtnActionPerformed(evt);
            }
        });
        menuPanel.add(image_notificationbtn);
        image_notificationbtn.setBounds(30, 480, 50, 40);

        signoutbtn.setBackground(new java.awt.Color(255, 255, 0));
        signoutbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        signoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/user.png"))); // NOI18N
        signoutbtn.setText("SIGN-OUT");
        signoutbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signoutbtn.setFocusPainted(false);
        signoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutbtnActionPerformed(evt);
            }
        });
        menuPanel.add(signoutbtn);
        signoutbtn.setBounds(30, 560, 200, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/YHLClogo - menuPanel.png"))); // NOI18N
        menuPanel.add(jLabel2);
        jLabel2.setBounds(30, 30, 190, 190);

        notificationbtn.setBackground(new java.awt.Color(204, 153, 0));
        notificationbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        notificationbtn.setText("Notification");
        notificationbtn.setBorder(null);
        notificationbtn.setFocusPainted(false);
        notificationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationbtnActionPerformed(evt);
            }
        });
        menuPanel.add(notificationbtn);
        notificationbtn.setBounds(80, 480, 150, 40);

        menuBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galleries/CashierMain/darkwood.jpg"))); // NOI18N
        menuPanel.add(menuBackgroundImage);
        menuBackgroundImage.setBounds(10, 0, 240, 650);

        mainbodyPanel.add(menuPanel);
        menuPanel.setBounds(0, -1, 250, 650);

        plotterPanel.setOpaque(false);
        mainbodyPanel.add(plotterPanel);
        plotterPanel.setBounds(250, 30, 930, 620);

        getContentPane().add(mainbodyPanel);
        mainbodyPanel.setBounds(-10, 0, 1180, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
       setActiveButton(homebtn);
       this.controller.displayComponents(plotterPanel, this.controller.getHome());
       StationSection.getLabel().setText("HOME");
    }//GEN-LAST:event_homebtnActionPerformed

    private void studentinfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentinfobtnActionPerformed
        setActiveButton(studentinfobtn);
        this.controller.displayComponents(plotterPanel, this.controller.getStudentInfo());
        StationSection.getLabel().setText("STUDENT INFO");
        
    }//GEN-LAST:event_studentinfobtnActionPerformed

    private void transactionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionbtnActionPerformed
        setActiveButton(transactionbtn);
        this.controller.displayComponents(plotterPanel, this.controller.getTransaction());
        StationSection.getLabel().setText("TRANSACTION");
       
       
    }//GEN-LAST:event_transactionbtnActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        setActiveButton(reportbtn);
        
        this.controller.displayComponents(plotterPanel, this.controller.getReport());
        StationSection.getLabel().setText("REPORT");
    }//GEN-LAST:event_reportbtnActionPerformed

    private void notificationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationbtnActionPerformed
          setActiveButton(notificationbtn);
          this.controller.displayComponents(plotterPanel, this.controller.getNotification());
           StationSection.getLabel().setText("NOTIFICATION");
    }//GEN-LAST:event_notificationbtnActionPerformed

    private void image_homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_homebtnActionPerformed
         setActiveButton(homebtn);
         this.controller.displayComponents(plotterPanel, this.controller.getHome());
    }//GEN-LAST:event_image_homebtnActionPerformed

    private void imageStudentInfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageStudentInfobtnActionPerformed
         setActiveButton(studentinfobtn);
         
         this.controller.displayComponents(plotterPanel, this.controller.getStudentInfo());
    }//GEN-LAST:event_imageStudentInfobtnActionPerformed

    private void image_transactionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_transactionbtnActionPerformed
        setActiveButton(transactionbtn);
      
        this.controller.displayComponents(plotterPanel, this.controller.getTransaction());
    }//GEN-LAST:event_image_transactionbtnActionPerformed

    private void image_reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_reportbtnActionPerformed
        setActiveButton(reportbtn);
        
        this.controller.displayComponents(plotterPanel, this.controller.getReport());
    }//GEN-LAST:event_image_reportbtnActionPerformed

    private void image_notificationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_notificationbtnActionPerformed
        setActiveButton(notificationbtn);
       
        this.controller.displayComponents(plotterPanel, this.controller.getNotification());
        
    }//GEN-LAST:event_image_notificationbtnActionPerformed

    private void signoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutbtnActionPerformed
        this.dispose();
        CashierLoginUI loginUI = new CashierLoginUI();
        int x = (int) loginUI.getLocation().getX();
        int y = (int) loginUI.getLocation().getY();
        loginUI.setLocation(x,y-70);
        loginUI.setVisible(true);
    }//GEN-LAST:event_signoutbtnActionPerformed

    private void minbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minbtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minbtnMouseClicked

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        
        
        try {
            if(!StationSection.getCurrentConnection().isClosed()){
                StationSection.getCurrentConnection().close();
            }
        } catch (SQLException ex) {
            
            CreateSection.displayErrorMessage("Error in closing connection of MYSQL", ex.toString());
            //Logger.getLogger(CashierMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
        CashierLoginUI loginUI = new CashierLoginUI();
        int x = (int) loginUI.getLocation().getX();
        int y = (int) loginUI.getLocation().getY();
        loginUI.setLocation(x,y-70);
        loginUI.setVisible(true);
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentPlacelbl;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton imageStudentInfobtn;
    private javax.swing.JButton image_homebtn;
    private javax.swing.JButton image_notificationbtn;
    private javax.swing.JButton image_reportbtn;
    private javax.swing.JButton image_transactionbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainbodyPanel;
    private javax.swing.JLabel menuBackgroundImage;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minbtn;
    private javax.swing.JButton notificationbtn;
    private javax.swing.JPanel plotterPanel;
    private javax.swing.JButton reportbtn;
    private javax.swing.JLabel schoolyearDisplayer;
    private javax.swing.JButton signoutbtn;
    private javax.swing.JButton studentinfobtn;
    private javax.swing.JLabel topBar;
    private javax.swing.JButton transactionbtn;
    private javax.swing.JPanel wholebodyPanel;
    // End of variables declaration//GEN-END:variables

    
    public void init(){
        new DesignSection().designForm(this, mainbodyPanel, "mini");
        this.controller = new CashierMainController();
        firstOpen();
        setMainDirectoryLabel("HOME");
        StationSection.setLabel(CurrentPlacelbl);
        StationSection.setSchoolYearDisplayer(schoolyearDisplayer);
        schoolyearDisplayer.setText(new SchoolYearController().getActiveSchoolYear().getSchoolYearName());
       
    }
   
    public void setActiveButton(JButton button){
        
        Color defaultbtnColor  = new Color(204,153,0);
        Color activebtnColor = new Color(247,220,111);
        int defaultheight = 40;
        int defaultWidth = 150;
        int activebtnWidth = 200;
        
        //first is to reset every menu button
        JButton[] menubuttons = {homebtn,studentinfobtn,transactionbtn,reportbtn,notificationbtn};
        for(JButton menubutton:menubuttons){
            menubutton.setSize(defaultWidth,defaultheight);
            menubutton.setBackground(defaultbtnColor);
            menubutton.setHorizontalTextPosition(SwingConstants.LEFT);
            menubutton.setEnabled(true);
        }
        
        //then change the active button width and color which is the parameter
     
        button.setBackground(activebtnColor);
        button.setSize(activebtnWidth, defaultheight);
        
        button.setEnabled(false);

       
        
    }
    public void firstOpen(){
         setActiveButton(homebtn);
       this.controller.displayComponents(plotterPanel, this.controller.getHome());
  
    }
    public void setMainDirectoryLabel(String title){
        CurrentPlacelbl.setText(title);
    
    }
    public String getMainDirectoryLabel(){
        return CurrentPlacelbl.getText();
    
    }
}
